config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root to: "movies#index"
  resources "aws_texts", only: [:index, :show]
  resources "questions", only: [:index, :create, :show]
  resources "lines", only: [:index]
  resources "movies", only: [:index]
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
end

app/models/line.rb
class Line < ApplicationRecord
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true
  validates :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
  validates :genre, presence: true
  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController
  def index
    @aws_texts = AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end
  
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  PER = 18

  def index
    if params[:genre] == nil
      @movies = Movie.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).page(params[:page]).per(PER)
    else
      @movies = Movie.where(genre: params[:genre]).page(params[:page]).per(PER)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @question = Question.new
  end

  def create
    Question.create!(question_params)
    redirect_to questions_path
  end

  def show
    @question = Question.find(params[:id])
  end

  private

  def question_params
    params.require(:question).permit(:title, :detail)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      language = language.split(":")[0] if language.present?

      case language.to_s
      when "rb"
        lang = :ruby
      when "yml"
        lang = :yaml
      when "css"
        lang = :css
      when "html"
        lang = :html
      when ""
        lang = :md
      else
        lang = language
      end

      CodeRay.scan(code, lang).div
    end
  end

  def markdown(text)
    html_render = HTMLwithCoderay.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: "nofollow", target: "_blank" },
    )
    options = {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true,
    }
    markdown = Redcarpet::Markdown.new(html_render, options)
    markdown.render(text)
  end

  def bg_color
    bg_color = controller.controller_name == "lines" ? "bg-success" : "bg-primary"
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/views/aws_texts/index.html.erb
<div class="mx-auto" style="width: 500px;">
  <h4 class="text-center pt-5 pb-1">AWS講座</h4>
  <p class="text-center h6">注意！！！：AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>

  <table class="table table-striped pb-3">
      <thead class="text-white bg-primary">
        <tr>
        <th>No</th>
        <th><%= "内容" %></th>
        </tr>
      </thead>
      <tbody>
        <% @aws_texts.each.with_index(1) do |aws_text,i| %>
          <tr>
          <th><%= i %></th>
          <th><%= link_to aws_text.title, aws_text %></th>
          </tr>
        <% end %>
      </tbody>
  </table>
</div>

app/views/aws_texts/show.html.erb
<h1>詳細</h1>
<p>タイトル <%= @aws_text.title %></p>

<%= markdown(@aws_text.content).html_safe %>

app/views/layouts/_flash.html.erb
<% flash.each do | flash_type, msg | %>
  <p class="alert alert-<%= flash_type %>">
    <%= msg %>
  </p>
<% end %>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-sm navbar-dark <%= bg_color %> fixed-bottom">
  <div class="collapse navbar-collapse justify-content-center">
    <div class="navbar-nav footer-text" >
      <%= link_to "ブログ", "https://utina.yoshitokamizato.com/", class: "nav-item nav-link active" %>
      <%= link_to "Youtube", "https://www.youtube.com/channel/UCwrDvYey9uKGBeh_l5IF-ag", class: "nav-item nav-link active" %>
    </div>
  </div>
</nav>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm navbar-dark <%= bg_color %> fixed-top">
  <span class="navbar-brand">やんばるCODE</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse justify-content-center" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <div class="nav-item dropdown">
        <%= link_to "Rails", "#",  class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLinkRails", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkRails">
            <%= link_to "Ruby/Rails", "#",  class: "dropdown-item" %>
            <%= link_to "動画教材", movies_path,  class: "dropdown-item" %>
            <%= link_to "AWS講座", "/aws_texts" ,  class: "dropdown-item" %>
            <%= link_to "ライブコーディング", movies_path(genre: "Live"),  class: "dropdown-item" %>
            <%= link_to "質問集", questions_path,  class: "dropdown-item" %>
          </div>
      </div>
      <%= link_to "対談", "#", class: "nav-item nav-link active" %>
      <%= link_to "情報発信", "#", class: "nav-item nav-link active" %>
      <%= link_to "ライティング講座", "#", class: "nav-item nav-link active"%>
      <%= link_to "マネタイズ講座", "#", class: "nav-item nav-link active"%>
      <div class="nav-item dropdown">
        <%= link_to "PHP", "#", class: "nav-link dropdown-toggle", id: "navbarDropdownMenuLinkPHP", role: "button", data: { toggle: "dropdown" }, aria: { haspopup: "true", expanded: "false" } %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLinkPHP">
            <%= link_to "PHPテキスト教材", "#",  class: "dropdown-item" %>
            <%= link_to "PHP動画教材", "#",  class: "dropdown-item" %>
        </div>
      </div>
      <%= link_to "LINE＠", lines_path, class: "nav-item nav-link active"%>
      <% if user_signed_in? %>
        <%= link_to "アカウント編集", edit_user_registration_path, class: "nav-item nav-link active"%>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-item nav-link active" %>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active"%> 
        <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active"%>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/header"%>
      <%= render "layouts/flash" %>
    </header>
    <main>
      <div class="base-container">
        <%= yield %>
      </div>
    </main>
    <footer>
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/lines/index.html.erb
<div class="row local-container">
  <div class="mx-auto">
    <h2 class="text-center text-success">LINE@</h2>
    <table class="table table-striped" style="font-size: 15pt;">
      <thead class="bg-success text-white">
        <tr>
          <th>No.</th>
          <th>ジャンル</th>
          <th>内容</th>
        </tr>
      </thead>
      <tbody>
        <% @lines.each do |line| %>
          <tr>
            <td><%= line.id %></td>
            <td><%= line.genre %></td>
            <td>
              <%= link_to line.title, lines_path(line) %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/movies/index.html.erb
<div class="row local-container">
  <% @movies.each do |movie| %>
    <div class="col-12 col-md-6 col-lg-4">
      <div class="card border-dark mb-3">
        <div class="embed-responsive embed-responsive-16by9">
          <iframe class="embed-responsive-item" src="<%= movie.url %>" allowfullscreen></iframe>
        </div>
        <div class="card-body">
          <a href="#" class="btn btn-secondary btn-block">視聴済みにする</a>
          <h5 class="card-title" style="padding-top: 10px;"><%= movie.title %></h5>
        </div>
      </div>
    </div>
  <% end %> 
</div>
<%= paginate @movies %>

app/views/questions/index.html.erb
<div class="container-login">
  <h1>新規投稿</h1>
  <%= form_with model: @question, local: true do |form| %>
    <div class="form-group">
      <p>【質問】</p>
      <%= form.text_area :title, class: "form-control", rows: 4 %>
    </div>
    <div class="form-group">
      <p>【詳細】</p>
      <%= form.text_area :content, class: "form-control", rows: 7 %>
    </div>
    <div>
      <%= form.submit "送信", class: "btn btn-primary btn-block" %> 
    </div>
  <% end %>
  <% @questions.each do |question| %>
    <%= link_to question do %>
      <div style="padding: 30px; margin-bottom: 10px; margin-top: 10px; border: 2px solid #333333; border-radius: 10px;">
        <div class="row question-wrapper">
          <div class="col-md-7 question-title">
            <h2><%= question.title %></h2>
          </div>
          <div class="col-md-5 question-date">
            <p>質問日  <%= l question.created_at, format: :short %></p>
          </div> 
        </div>
      </div>
    <% end %> 
  <% end %>
</div> 

app/views/questions/show.html.erb
<h3>【質問】</h3>
  <%= @question.title %>
<h3>【詳細】</h3>
  <%= @question.detail %>